lang: ru-RU
encoding: utf-8
domain: vitaliy-mironov.github.io
url: https://vitaliy-mironov.github.io
permalink: pretty
highlighter: rouge
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
